#!/bin/bash

function get_clip_cmd() {
 os=`uname`
      case $os in
        # Mac OS X
        Darwin*)
          pbpaste;;
        # Linux
        Linux*)
          if [ -z "$DISPLAY" ] ; then
              cclip
          else
              xclip -o
          fi
          ;;
        *)
          error "unsupported os $os";;
      esac
}

get_clip_cmd $@
